set(headers
        include/cubpackpp/atomic.h
        include/cubpackpp/atomreg.h
        include/cubpackpp/boolean.h
        include/cubpackpp/C2dv2.h
        include/cubpackpp/C2dv4.h
        include/cubpackpp/C2.h
        include/cubpackpp/C2interf.h
        include/cubpackpp/C2prc.h
        include/cubpackpp/C2rule13.h
        include/cubpackpp/C2togr.h
        include/cubpackpp/C2toS2.h
        include/cubpackpp/chrono.h
        include/cubpackpp/compreg.h
        include/cubpackpp/counter.h
        include/cubpackpp/cubpackpp.h
        include/cubpackpp/div.h
        include/cubpackpp/E2adapt.h
        include/cubpackpp/E2.h
        include/cubpackpp/E2interf.h
        include/cubpackpp/E2sec.h
        include/cubpackpp/E2secitf.h
        include/cubpackpp/E2secprc.h
        include/cubpackpp/E2tostrp.h
        include/cubpackpp/error.h
        include/cubpackpp/eval_ctr.h
        include/cubpackpp/function.h
        include/cubpackpp/geometry.h
        include/cubpackpp/gr.h
        include/cubpackpp/gritf.h
        include/cubpackpp/gs.h
        include/cubpackpp/gsitf.h
        include/cubpackpp/gsprc.h
        include/cubpackpp/heap.h
        include/cubpackpp/integran.h
        include/cubpackpp/integrat.h
        include/cubpackpp/invert.h
        include/cubpackpp/outS2.h
        include/cubpackpp/outS2itf.h
        include/cubpackpp/passbuck.h
        include/cubpackpp/patchlevel.h
        include/cubpackpp/point2D.h
        include/cubpackpp/pointer.h
        include/cubpackpp/point.h
        include/cubpackpp/polC2.h
        include/cubpackpp/polC2itf.h
        include/cubpackpp/polC2prc.h
        include/cubpackpp/ps.h
        include/cubpackpp/psitf.h
        include/cubpackpp/real.h
        include/cubpackpp/refcount.h
        include/cubpackpp/regcoll.h
        include/cubpackpp/reginfo.h
        include/cubpackpp/region.h
        include/cubpackpp/regproc.h
        include/cubpackpp/rule.h
        include/cubpackpp/S2adapt.h
        include/cubpackpp/S2.h
        include/cubpackpp/S2interf.h
        include/cubpackpp/S2rule13.h
        include/cubpackpp/s_adapt.h
        include/cubpackpp/samediv.h
        include/cubpackpp/semistrp.h
        include/cubpackpp/semstitf.h
        include/cubpackpp/set.h
        include/cubpackpp/stack.h
        include/cubpackpp/strip.h
        include/cubpackpp/stripitf.h
        include/cubpackpp/sttosmst.h
        include/cubpackpp/T2dv4.h
        include/cubpackpp/T2.h
        include/cubpackpp/T2interf.h
        include/cubpackpp/T2rule13.h
        include/cubpackpp/T2tops.h
        include/cubpackpp/templist.h
        include/cubpackpp/tools.h
        include/cubpackpp/translat.h
        include/cubpackpp/trnsfrm.h
        include/cubpackpp/userint.h
        include/cubpackpp/vector.h
        include/cubpackpp/vstack.h

        )

set(templates
        include/cubpackpp/atomic.tpp
        include/cubpackpp/div.tpp
        include/cubpackpp/heap.tpp
        include/cubpackpp/passbuck.tpp
        include/cubpackpp/pointer.tpp
        include/cubpackpp/regproc.tpp
        include/cubpackpp/rule.tpp
        include/cubpackpp/s_adapt.tpp
        include/cubpackpp/samediv.tpp
        include/cubpackpp/set.tpp
        include/cubpackpp/stack.tpp
        include/cubpackpp/userint.tpp
        include/cubpackpp/vector.tpp
        include/cubpackpp/vstack.tpp

        )

set(sources
        src/atomreg.cpp
        src/boolean.cpp
        src/C2.cpp
        src/C2dv2.cpp
        src/C2dv4.cpp
        src/C2interf.cpp
        src/C2prc.cpp
        src/C2rule13.cpp
        src/C2togr.cpp
        src/C2toS2.cpp
        src/chrono.cpp
        src/compreg.cpp
        src/deccxxtp.cpp
        src/E2adapt.cpp
        src/E2.cpp
        src/E2interf.cpp
        src/E2sec.cpp
        src/E2secitf.cpp
        src/E2secprc.cpp
        src/E2tostrp.cpp
        src/eval_ctr.cpp
        src/geometry.cpp
        src/gnu262tp.cpp
        src/gr.cpp
        src/gritf.cpp
        src/gs.cpp
        src/gsitf.cpp
        src/gsprc.cpp
        src/integran.cpp
        src/integrat.cpp
        src/invert.cpp
        src/outS2.cpp
        src/outS2itf.cpp
        src/point2D.cpp
        src/polC2.cpp
        src/polC2itf.cpp
        src/polC2prc.cpp
        src/ps.cpp
        src/psitf.cpp
        src/refcount.cpp
        src/regcoll.cpp
        src/reginfo.cpp
        src/region.cpp
        src/S2adapt.cpp
        src/S2.cpp
        src/S2interf.cpp
        src/S2rule13.cpp
        src/semistrp.cpp
        src/semstitf.cpp
        src/strip.cpp
        src/stripitf.cpp
        src/sttosmst.cpp
        src/T2.cpp
        src/T2dv4.cpp
        src/T2interf.cpp
        src/T2rule13.cpp
        src/T2tops.cpp
        src/translat.cpp
        src/trnsfrm.cpp

        )




